[package]
name = "httm"
version = "0.13.4"
edition = "2021"
keywords = ["zfs", "backup", "restore", "cli-utility", "snapshot"]
description = "A CLI tool for viewing snapshot file versions on ZFS and btrfs datasets"
repository = "https://github.com/kimono-koans/httm"
readme = "README.md"
categories = [ "command-line-utilities",  "os" ]
license = "MPL-2.0"
documentation = "https://github.com/kimono-koans/httm/blob/master/README.md"

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
strip = true
opt-level = "z"  # Aggressively optimize for size.
lto = true

[dependencies]
clap = { version = "3.2.8", features = ["cargo"] }
chrono = { version = "0.4.19", default-features = false }
number_prefix = { version = "0.4.0",  default-features = false }
skim = { version = "0.9.4", default-features = false }
lscolors = { version = "0.10.0", features = ["ansi_term"] }
terminal_size = { version = "0.2.0", default-features = false }
which = { version = "4.2.4", default-features = false }
rayon = { version = "1.5.1", default-features = false }
itertools = "0.10.3" # use_std, use_alloc for into_group_map_by()
indicatif =  { version = "0.16.2", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
proc-mounts = { version = "0.3.0", default-features = false }
ahash = { version = "0.7.6", default-features = false }
once_cell = { version = "1.13.0", default-features = false }
moka = "0.9"

[package.metadata.deb]
maintainer = "kimono koans <https://github.com/kimono-koans/>"
copyright = "2022, Robert Swinford <robert.swinford<...at...>gmail.com>"
extended-description = """\
httm prints the size, date and corresponding locations of available unique versions of files
residing on snapshots.  May also be used interactively to select and restore from such
versions, and even to snapshot datasets which contain certain files.
"""
license-file = ["LICENSE", "4"]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/httm", "usr/bin/", "755"],
    ["httm.1", "usr/share/man/man1/", "644"],
    ["README.md", "usr/share/doc/httm/README", "644"],
]